apiVersion: velero.io/v1
kind: Schedule
metadata:
  namespace: openshift-adp
  name: schedule-mq
spec:
  schedule: 0 */1 * * *
  template:
    defaultVolumesToRestic: false
    includedResources:
      - persistentvolumes
      - persistentvolumeclaims
      - pods
      - serviceaccounts
    ttl: 2h0m0s
    includeClusterResources: true
    labelSelector:
      matchLabels:
        app.kubernetes.io/instance: chechu-queue-1
    includedNamespaces:
      - cloudpak
    snapshotVolumes: true
    excludedResources:
      - steatefulsets
      - queuemanagers
      - clients
