apiVersion: v2
name: mq-instance-dr
description: Deployment of MQ instance
type: application
version: 0.1.10
appVersion: "0.1.10"
dependencies:
  - name: mq-instance-dr
    version: 0.1.10
    repository: https://chechuironman.github.io/helm-repo/


